// web/src/pages/Home.svelte
<script lang="ts">
import { getLeaderboard, type PlayerStats } from '../lib/api/index.ts'

const currentYear = new Date().getFullYear()

    let matchType = $state('indoor')
let season = $state(currentYear)
    let leaderboard: PlayerStats[] = $state([])
let loading = $state(false)
    let error = $state('')

    // Sorting
    let sortColumn = $state('points')
    let sortDir = $state<'asc' | 'desc'>('desc')

    async function fetchLeaderboard() {
        loading = true
            error = ''
            try {
                leaderboard = await getLeaderboard(matchType, season)
            } catch {
                error = 'Failed to load leaderboard.'
            } finally {
                loading = false
            }
    }

$effect(() => {
        matchType
        season
        fetchLeaderboard()
        })

function toggleSort(col: string) {
    if (sortColumn === col) {
        sortDir = sortDir === 'asc' ? 'desc' : 'asc'
    } else {
        sortColumn = col
            sortDir = 'desc'
    }
}

function sortIcon(col: string): string {
    if (sortColumn !== col) return '↕'
        return sortDir === 'asc' ? '↑' : '↓'
}

const sorted = $derived(() => {
        return [...leaderboard].sort((a, b) => {
                const aVal = (a as any)[sortColumn]
                const bVal = (b as any)[sortColumn]
                if (typeof aVal === 'string') {
                return sortDir === 'asc'
                ? aVal.localeCompare(bVal)
                : bVal.localeCompare(aVal)
                }
                return sortDir === 'asc' ? aVal - bVal : bVal - aVal
                })
        })

function calculateMmr(avgPoints: number, efficiencyRate: number): number {
    return avgPoints * efficiencyRate
}

function getRank(played: number, points: number, efficiencyRate: number): string {
    if (played < 10) return 'Unranked'
        const avgPoints = played > 0 ? points / played : 0
            const mmr = calculateMmr(avgPoints, efficiencyRate)
            const ranks: [string, number, number][] = [
            ['Iron I',       0,    0.1],
            ['Iron II',      0.1,  0.2],
            ['Iron III',     0.2,  0.3],
            ['Bronze I',     0.3,  0.4],
            ['Bronze II',    0.4,  0.5],
            ['Bronze III',   0.5,  0.6],
            ['Silver I',     0.6,  0.7],
            ['Silver II',    0.7,  0.8],
            ['Silver III',   0.8,  0.9],
            ['Gold I',       0.9,  1.0],
            ['Gold II',      1.0,  1.1],
            ['Gold III',     1.1,  1.2],
            ['Platinum I',   1.2,  1.3],
            ['Platinum II',  1.3,  1.4],
            ['Platinum III', 1.4,  1.5],
            ['Diamond I',    1.5,  1.6],
            ['Diamond II',   1.6,  1.7],
            ['Diamond III',  1.7,  1.8],
            ['Spiker',       1.8,  1.9],
            ['Ace',          1.9,  2.0],
            ['Sensei',       2.0,  Infinity],
            ]
                for (const [name, low, high] of ranks) {
                    if (mmr >= low && mmr < high) return name
                }
            return 'Iron I'
}
</script>

<div class="page">
<h1>🏆 Leaderboard</h1>

<div class="filters">
<select bind:value={matchType}>
<option value="indoor">Indoor</option>
<option value="beach">Beach</option>
</select>
<input type="number" min="2023" max={currentYear} bind:value={season} />
</div>

{#if loading}
<p>Loading...</p>
{:else if error}
<p class="error">{error}</p>
{:else if leaderboard.length === 0}
<p>No stats for {matchType} in season {season}.</p>
{:else}
<table>
<thead>
<tr>
<th>#</th>
{#each [
    { key: 'name', label: 'Player' },
        { key: 'played', label: 'Played' },
        { key: 'wins', label: 'Wins' },
        { key: 'losses', label: 'Losses' },
        { key: 'otl', label: 'OTL' },
        { key: 'points', label: 'Points' },
        { key: 'win_rate', label: 'Win Rate' },
        { key: 'rank', label: 'Rank' },
] as col}
<th onclick={() => toggleSort(col.key)} class="sortable">
{col.label} <span class="sort-icon">{sortIcon(col.key)}</span>
</th>
{/each}
</tr>
</thead>
<tbody>
{#each sorted() as player, index}
<tr>
<td>{index + 1}</td>
<td>{player.name}</td>
<td>{player.played}</td>
<td>{player.wins}</td>
<td>{player.losses}</td>
<td>{player.otl}</td>
<td>{player.points}</td>
<td>{(player.win_rate * 100).toFixed(1)}%</td>
<td>{getRank(player.played, player.points, player.efficiency_rate)}</td>
</tr>
{/each}
</tbody>
</table>
{/if}
</div>

<style>
.page {
padding: 2rem;
}

.filters {
display: flex;
gap: 1rem;
     margin-bottom: 1.5rem;
}

select, input {
padding: 0.5rem;
         font-size: 1rem;
         border-radius: 4px;
border: 1px solid #ccc;
}

table {
width: 100%;
       border-collapse: collapse;
}

th, td {
    text-align: left;
padding: 0.75rem 1rem;
         border-bottom: 1px solid #eee;
}

th {
    font-weight: 600;
background: #1a1a2e;
color: white;
}

th.sortable {
cursor: pointer;
        user-select: none;
}

th.sortable:hover {
background: #2a2a3e;
}

.sort-icon {
    font-size: 0.8rem;
opacity: 0.7;
         margin-left: 0.25rem;
}

tr:hover {
background: #f5f5f5;
   }

.error { color: red; }
</style>

// web/src/pages/Home.tsx
import { useEffect, useMemo, useState } from 'react'
import { getLeaderboard, type PlayerStats } from '../lib/api'
import { getRank } from '../lib/rank'

const currentYear = new Date().getFullYear()

type SortKey = keyof PlayerStats | 'rank'
type SortDir = 'asc' | 'desc'

const columns: { key: SortKey; label: string }[] = [
  { key: 'name', label: 'Player' },
  { key: 'played', label: 'Played' },
  { key: 'wins', label: 'Wins' },
  { key: 'losses', label: 'Losses' },
  { key: 'otl', label: 'OTL' },
  { key: 'points', label: 'Points' },
  { key: 'win_rate', label: 'Win Rate' },
  { key: 'rank', label: 'Rank' },
]

export default function Home() {
  const [matchType, setMatchType] = useState('indoor')
  const [season, setSeason] = useState(currentYear)
  const [leaderboard, setLeaderboard] = useState<PlayerStats[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [sortColumn, setSortColumn] = useState<SortKey>('points')
  const [sortDir, setSortDir] = useState<SortDir>('desc')

  useEffect(() => {
    let cancelled = false
    setLoading(true)
    setError('')
    getLeaderboard(matchType, season)
      .then((data) => {
        if (!cancelled) setLeaderboard(data)
      })
      .catch(() => {
        if (!cancelled) setError('Failed to load leaderboard.')
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [matchType, season])

  function toggleSort(col: SortKey) {
    if (sortColumn === col) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'))
    } else {
      setSortColumn(col)
      setSortDir('desc')
    }
  }

  function sortIcon(col: SortKey) {
    if (sortColumn !== col) return '↕'
    return sortDir === 'asc' ? '↑' : '↓'
  }

  const sorted = useMemo(() => {
    return [...leaderboard].sort((a, b) => {
      if (sortColumn === 'rank') {
        const aRank = getRank(a.played, a.points, a.efficiency_rate)
        const bRank = getRank(b.played, b.points, b.efficiency_rate)
        return sortDir === 'asc' ? aRank.localeCompare(bRank) : bRank.localeCompare(aRank)
      }
      const aVal = a[sortColumn]
      const bVal = b[sortColumn]
      if (typeof aVal === 'string' && typeof bVal === 'string') {
        return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal)
      }
      return sortDir === 'asc'
        ? (aVal as number) - (bVal as number)
        : (bVal as number) - (aVal as number)
    })
  }, [leaderboard, sortColumn, sortDir])

  return (
    <div>
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-semibold tracking-tight text-slate-900">
          🏆 Leaderboard
        </h1>

        <div className="flex gap-3">
          <select
            value={matchType}
            onChange={(e) => setMatchType(e.target.value)}
            className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
          >
            <option value="indoor">Indoor</option>
            <option value="beach">Beach</option>
          </select>
          <input
            type="number"
            min={2023}
            max={currentYear}
            value={season}
            onChange={(e) => setSeason(Number(e.target.value))}
            className="w-28 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm text-slate-700 shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
          />
        </div>
      </div>

      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        {loading ? (
          <p className="p-6 text-sm text-slate-500">Loading...</p>
        ) : error ? (
          <p className="p-6 text-sm text-red-600">{error}</p>
        ) : leaderboard.length === 0 ? (
          <p className="p-6 text-sm text-slate-500">
            No stats for {matchType} in season {season}.
          </p>
        ) : (
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="bg-brand-bg text-white">
                <th className="px-4 py-3 text-left font-medium">#</th>
                {columns.map((col) => (
                  <th
                    key={col.key}
                    onClick={() => toggleSort(col.key)}
                    className="cursor-pointer select-none px-4 py-3 text-left font-medium transition-colors hover:bg-brand-bg-hover"
                  >
                    {col.label}{' '}
                    <span className="ml-0.5 text-xs opacity-70">{sortIcon(col.key)}</span>
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {sorted.map((player, index) => (
                <tr
                  key={player.id}
                  className="border-b border-slate-100 last:border-0 hover:bg-slate-50"
                >
                  <td className="px-4 py-3 text-slate-500">{index + 1}</td>
                  <td className="px-4 py-3 font-medium text-slate-900">{player.name}</td>
                  <td className="px-4 py-3">{player.played}</td>
                  <td className="px-4 py-3">{player.wins}</td>
                  <td className="px-4 py-3">{player.losses}</td>
                  <td className="px-4 py-3">{player.otl}</td>
                  <td className="px-4 py-3">{player.points}</td>
                  <td className="px-4 py-3">{(player.win_rate * 100).toFixed(1)}%</td>
                  <td className="px-4 py-3">
                    <span className="inline-flex items-center rounded-full bg-brand-accent/10 px-2.5 py-0.5 text-xs font-medium text-brand-accent">
                      {getRank(player.played, player.points, player.efficiency_rate)}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
