// web/src/pages/Login.svelte
<script lang="ts">
import { login } from '../lib/api/index.ts'
import { auth } from '../lib/auth.svelte.ts'

let email = $state('')
let password = $state('')
    let error = $state('')
let loading = $state(false)

    async function handleLogin() {
        error = ''
            loading = true
            try {
                const token = await login(email, password)
                    auth.login(token)
            } catch {
                error = 'Invalid email or password.'
            } finally {
                loading = false
            }
    }
</script>

<div class="page">
<div class="login-card">
<h1>🔐 Admin Login</h1>

{#if auth.isAuthenticated}
<p class="success">✅ Logged in</p>
<button onclick={() => auth.logout()}>Logout</button>
{:else}
<div class="form">
<input
type="email"
placeholder="Email"
bind:value={email}
/>
<input
type="password"
placeholder="Password"
bind:value={password}
/>
<button onclick={handleLogin} disabled={loading || !email || !password}>
{loading ? 'Logging in...' : 'Login'}
</button>
</div>
{#if error}<p class="error">{error}</p>{/if}
{/if}
</div>
</div>

<style>
.page {
padding: 2rem;
display: flex;
         justify-content: center;
}

.login-card {
width: 100%;
       max-width: 400px;
padding: 2rem;
border: 1px solid #eee;
        border-radius: 12px;
background: #1a1a2e;
}

.form {
display: flex;
         flex-direction: column;
gap: 1rem;
}

input {
padding: 0.5rem;
         font-size: 1rem;
         border-radius: 4px;
border: 1px solid #ccc;
}

button {
padding: 0.5rem 1rem;
         border-radius: 4px;
border: none;
cursor: pointer;
background: #ff6b35;
color: white;
       font-size: 1rem;
}

button:disabled {
opacity: 0.5;
cursor: not-allowed;
       }

.success { color: green; }
.error { color: red; }
</style>

// web/src/pages/Login.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { login } from '../lib/api'
import { useAuth } from '../lib/AuthContext'

export default function Login() {
  const auth = useAuth()
  const navigate = useNavigate()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  async function handleLogin() {
    setError('')
    setLoading(true)
    try {
      const token = await login(email, password)
      auth.login(token)
      navigate('/')
    } catch {
      setError('Invalid email or password.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex justify-center">
      <div className="w-full max-w-sm rounded-2xl bg-brand-bg p-8 text-white shadow-sm">
        <h1 className="mb-6 text-xl font-semibold">Admin</h1>

        {auth.isAuthenticated ? (
          <>
            <p className="mb-4 text-sm text-emerald-400">Logged in</p>
            <button
              onClick={() => auth.logout()}
              className="w-full rounded-lg border border-slate-600 px-4 py-2 text-sm font-medium transition-colors hover:bg-brand-bg-hover"
            >
              Logout
            </button>
          </>
        ) : (
          <>
            <div className="flex flex-col gap-3">
              <input
                type="email"
                placeholder="Email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && !loading && email && password && handleLogin()}
                className="rounded-lg border border-slate-600 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-slate-400 focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
              />
              <input
                type="password"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && !loading && email && password && handleLogin()}
                className="rounded-lg border border-slate-600 bg-white/5 px-3 py-2 text-sm text-white placeholder:text-slate-400 focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
              />
              <button
                onClick={handleLogin}
                disabled={loading || !email || !password}
                className="rounded-lg bg-brand-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-brand-accent-hover disabled:cursor-not-allowed disabled:opacity-50"
              >
                {loading ? 'Logging in...' : 'Login'}
              </button>
            </div>
            {error && <p className="mt-3 text-sm text-red-400">{error}</p>}
          </>
        )}
      </div>
    </div>
  )
}
