// web/src/pages/Players.tsx
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import {
  getPlayers,
  getPlayerStats,
  getPlayerHistory,
  createPlayer,
  updatePlayerName,
  deletePlayer,
  type Player,
  type PlayerStats,
  type MatchHistory,
} from '../lib/api'
import { getRank } from '../lib/rank'
import { useAuth } from '../lib/AuthContext'

const currentYear = new Date().getFullYear()

type Tab = 'profile' | 'add' | 'manage'

function delta(
  current: number,
  previous: number | null
): { text: string; type: 'positive' | 'negative' | 'neutral' } {
  if (previous === null) return { text: '', type: 'neutral' }
  const diff = current - previous
  if (diff === 0) return { text: '±0', type: 'neutral' }
  return diff > 0 ? { text: `+${diff}`, type: 'positive' } : { text: `${diff}`, type: 'negative' }
}

const deltaColor = {
  positive: 'text-emerald-600',
  negative: 'text-red-600',
  neutral: 'text-slate-400',
}

export default function Players() {
  const auth = useAuth()
  const [activeTab, setActiveTab] = useState<Tab>('profile')

  const [players, setPlayers] = useState<Player[]>([])
  const [loadingPlayers, setLoadingPlayers] = useState(false)

  async function fetchPlayers() {
    setLoadingPlayers(true)
    try {
      setPlayers(await getPlayers())
    } catch (e) {
      console.error(e)
    } finally {
      setLoadingPlayers(false)
    }
  }

  useEffect(() => {
    fetchPlayers()
  }, [])

  // --- Profile tab state ---
  const [selectedPlayerId, setSelectedPlayerId] = useState('')
  const [matchType, setMatchType] = useState('indoor')
  const [season, setSeason] = useState(currentYear)
  const [stats, setStats] = useState<PlayerStats | null>(null)
  const [prevStats, setPrevStats] = useState<PlayerStats | null>(null)
  const [history, setHistory] = useState<MatchHistory[]>([])
  const [loadingStats, setLoadingStats] = useState(false)
  const [statsError, setStatsError] = useState('')

  useEffect(() => {
    if (!selectedPlayerId) return
    let cancelled = false

    async function fetchStats() {
      setLoadingStats(true)
      setStatsError('')
      try {
        const s = await getPlayerStats(selectedPlayerId, matchType, season)
        const h = await getPlayerHistory(selectedPlayerId, matchType, season)
        if (cancelled) return
        setStats(s)
        setHistory(h)
        try {
          const p = await getPlayerStats(selectedPlayerId, matchType, season - 1)
          if (!cancelled) setPrevStats(p)
        } catch {
          if (!cancelled) setPrevStats(null)
        }
      } catch {
        if (!cancelled) {
          setStatsError('Failed to load player stats.')
          setStats(null)
        }
      } finally {
        if (!cancelled) setLoadingStats(false)
      }
    }

    fetchStats()
    return () => {
      cancelled = true
    }
  }, [selectedPlayerId, matchType, season])

  // --- Add player tab state ---
  const [newPlayerName, setNewPlayerName] = useState('')
  const [addSuccess, setAddSuccess] = useState('')
  const [addError, setAddError] = useState('')

  async function handleAddPlayer() {
    setAddSuccess('')
    setAddError('')
    try {
      await createPlayer(newPlayerName)
      setAddSuccess(`✅ Added ${newPlayerName}`)
      setNewPlayerName('')
      await fetchPlayers()
    } catch {
      setAddError('Failed to add player.')
    }
  }

  // --- Manage players tab state ---
  const [managePlayerId, setManagePlayerId] = useState('')
  const [newName, setNewName] = useState('')
  const [manageSuccess, setManageSuccess] = useState('')
  const [manageError, setManageError] = useState('')

  async function handleRename() {
    setManageSuccess('')
    setManageError('')
    try {
      await updatePlayerName(managePlayerId, newName)
      setManageSuccess('✅ Renamed successfully')
      await fetchPlayers()
    } catch {
      setManageError('Failed to rename player.')
    }
  }

  async function handleDelete() {
    setManageSuccess('')
    setManageError('')
    try {
      await deletePlayer(managePlayerId)
      setManageSuccess('✅ Player deleted')
      setManagePlayerId('')
      await fetchPlayers()
    } catch {
      setManageError('Failed to delete player.')
    }
  }

  return (
    <div>
      <h1 className="mb-6 text-2xl font-semibold tracking-tight text-slate-900">
        👥 Players
      </h1>

      <div className="mb-6 flex gap-1 border-b border-slate-200">
        {(
          [
            ['profile', 'Player Profile'],
            ['add', 'Add Player'],
            ['manage', 'Manage Players'],
          ] as [Tab, string][]
        ).map(([tab, label]) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={[
              'rounded-t-lg px-4 py-2 text-sm font-medium transition-colors',
              activeTab === tab
                ? 'border-b-2 border-brand-accent text-brand-accent'
                : 'text-slate-500 hover:text-slate-800',
            ].join(' ')}
          >
            {label}
          </button>
        ))}
      </div>

      {activeTab === 'profile' && (
        <div>
          {loadingPlayers ? (
            <p className="text-sm text-slate-500">Loading players...</p>
          ) : players.length === 0 ? (
            <p className="text-sm text-slate-500">No players yet!</p>
          ) : (
            <>
              <div className="mb-6 flex gap-3">
                <select
                  value={selectedPlayerId}
                  onChange={(e) => setSelectedPlayerId(e.target.value)}
                  className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
                >
                  <option value="">Select a player</option>
                  {players.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name}
                    </option>
                  ))}
                </select>
                <select
                  value={matchType}
                  onChange={(e) => setMatchType(e.target.value)}
                  className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
                >
                  <option value="indoor">Indoor</option>
                  <option value="beach">Beach</option>
                </select>
                <input
                  type="number"
                  min={2023}
                  max={currentYear}
                  value={season}
                  onChange={(e) => setSeason(Number(e.target.value))}
                  className="w-28 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
                />
              </div>

              {!selectedPlayerId ? (
                <p className="text-sm text-slate-500">Select a player to view their stats.</p>
              ) : loadingStats ? (
                <p className="text-sm text-slate-500">Loading stats...</p>
              ) : statsError ? (
                <p className="text-sm text-red-600">{statsError}</p>
              ) : stats ? (
                <>
                  <div className="mb-8 grid grid-cols-4 gap-4">
                    {[
                      { label: 'Matches Played', value: stats.played, prev: prevStats?.played ?? null },
                      { label: 'Wins', value: stats.wins, prev: prevStats?.wins ?? null },
                      { label: 'Losses', value: stats.losses, prev: prevStats?.losses ?? null },
                      { label: 'OTL', value: stats.otl, prev: prevStats?.otl ?? null },
                      { label: 'Points', value: stats.points, prev: prevStats?.points ?? null },
                      {
                        label: 'Win Rate',
                        value: Math.round(stats.win_rate * 100),
                        prev: prevStats ? Math.round(prevStats.win_rate * 100) : null,
                        suffix: '%',
                      },
                      { label: 'Win Streak', value: stats.streak, prev: null },
                      {
                        label: 'Longest Streak',
                        value: stats.longest_streak,
                        prev: prevStats?.longest_streak ?? null,
                      },
                    ].map((stat) => {
                      const d = delta(stat.value, stat.prev)
                      return (
                        <div
                          key={stat.label}
                          className="flex flex-col rounded-xl bg-brand-bg p-4 text-white"
                        >
                          <span className="text-xs text-slate-400">{stat.label}</span>
                          <span className="text-2xl font-semibold">
                            {stat.value}
                            {stat.suffix ?? ''}
                          </span>
                          {d.text && (
                            <span className={`mt-1 text-xs font-medium ${deltaColor[d.type]}`}>
                              {d.text}
                            </span>
                          )}
                        </div>
                      )
                    })}
                  </div>

                  <div className="mb-8 flex flex-col items-center gap-1">
                    <h3 className="text-sm font-medium text-slate-500">Rank</h3>
                    <span className="inline-flex items-center rounded-full bg-brand-accent/10 px-3 py-1 text-lg font-semibold text-brand-accent">
                      {getRank(stats.played, stats.points, stats.efficiency_rate)}
                    </span>
                  </div>

                  <div>
                    <h3 className="mb-3 text-sm font-medium text-slate-500">Match History</h3>
                    {history.length === 0 ? (
                      <p className="text-sm text-slate-500">No completed matches this season.</p>
                    ) : (
                      <div className="space-y-2">
                        {history.map((match) => {
                          const myScore = match.color === 'blue' ? match.blue_score : match.red_score
                          const theirScore = match.color === 'blue' ? match.red_score : match.blue_score
                          const won = myScore > theirScore
                          const isOtl = Math.abs(match.blue_score - match.red_score) === 2 && !won
                          const rowClass = won
                            ? 'bg-emerald-50 text-emerald-700'
                            : isOtl
                              ? 'bg-amber-50 text-amber-700'
                              : 'bg-red-50 text-red-700'
                          return (
                            <div
                              key={match.id}
                              className={`flex items-center gap-8 rounded-lg px-4 py-2 text-sm ${rowClass}`}
                            >
                              <span>{won ? '✅ Win' : isOtl ? '⚠️ OTL' : '❌ Loss'}</span>
                              <span>
                                {myScore} : {theirScore}
                              </span>
                              <span className="capitalize">{match.color} team</span>
                              <span>{match.created_at.slice(0, 10)}</span>
                            </div>
                          )
                        })}
                      </div>
                    )}
                  </div>
                </>
              ) : null}
            </>
          )}
        </div>
      )}

      {activeTab === 'add' && (
        <div className="max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="mb-4 text-lg font-semibold text-slate-900">Add New Player</h2>
          {auth.isAuthenticated ? (
            <>
              <div className="flex gap-3">
                <input
                  type="text"
                  placeholder="Player name"
                  value={newPlayerName}
                  onChange={(e) => setNewPlayerName(e.target.value)}
                  className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
                />
                <button
                  onClick={handleAddPlayer}
                  disabled={!newPlayerName}
                  className="rounded-lg bg-brand-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-brand-accent-hover disabled:cursor-not-allowed disabled:opacity-50"
                >
                  Add Player
                </button>
              </div>
              {addSuccess && <p className="mt-3 text-sm text-emerald-600">{addSuccess}</p>}
              {addError && <p className="mt-3 text-sm text-red-600">{addError}</p>}
            </>
          ) : (
            <p className="text-sm text-slate-500">
              You must be{' '}
              <Link to="/login" className="text-brand-accent hover:underline">
                logged in
              </Link>{' '}
              to add players.
            </p>
          )}
        </div>
      )}

      {activeTab === 'manage' && (
        <div className="max-w-md rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="mb-4 text-lg font-semibold text-slate-900">Manage Players</h2>
          {!auth.isAuthenticated ? (
            <p className="text-sm text-slate-500">
              You must be{' '}
              <Link to="/login" className="text-brand-accent hover:underline">
                logged in
              </Link>{' '}
              to manage players.
            </p>
          ) : players.length === 0 ? (
            <p className="text-sm text-slate-500">No players to manage.</p>
          ) : (
            <>
              <select
                value={managePlayerId}
                onChange={(e) => setManagePlayerId(e.target.value)}
                className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
              >
                <option value="">Select a player</option>
                {players.map((p) => (
                  <option key={p.id} value={p.id}>
                    {p.name}
                  </option>
                ))}
              </select>

              {managePlayerId && (
                <div className="mt-6 space-y-6">
                  <div>
                    <h3 className="mb-2 text-sm font-medium text-slate-700">✏️ Rename</h3>
                    <div className="flex gap-3">
                      <input
                        type="text"
                        placeholder="New name"
                        value={newName}
                        onChange={(e) => setNewName(e.target.value)}
                        className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm shadow-sm focus:border-brand-accent focus:outline-none focus:ring-2 focus:ring-brand-accent/30"
                      />
                      <button
                        onClick={handleRename}
                        disabled={!newName}
                        className="rounded-lg bg-brand-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-brand-accent-hover disabled:cursor-not-allowed disabled:opacity-50"
                      >
                        Rename
                      </button>
                    </div>
                  </div>

                  <div className="rounded-lg border border-red-200 bg-red-50 p-4">
                    <h3 className="mb-1 text-sm font-medium text-red-700">🗑️ Delete</h3>
                    <p className="mb-3 text-sm text-red-600">
                      This will permanently delete this player.
                    </p>
                    <button
                      onClick={handleDelete}
                      className="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-red-700"
                    >
                      Confirm Delete
                    </button>
                  </div>
                </div>
              )}

              {manageSuccess && <p className="mt-4 text-sm text-emerald-600">{manageSuccess}</p>}
              {manageError && <p className="mt-4 text-sm text-red-600">{manageError}</p>}
            </>
          )}
        </div>
      )}
    </div>
  )
}

// web/src/pages/Players.svelte
<script lang="ts">
import { auth } from '../lib/auth.svelte.ts'
import { getPlayers, getPlayerStats, getPlayerHistory, createPlayer, updatePlayerName, deletePlayer, type Player, type PlayerStats, type MatchHistory } from '../lib/api/index.ts'

const currentYear = new Date().getFullYear()

    let activeTab = $state('profile')

    let players: Player[] = $state([])
let loadingPlayers = $state(false)

    async function fetchPlayers() {
        loadingPlayers = true
            try {
                players = await getPlayers()
            } catch (e) {
                console.error(e)
            } finally {
                loadingPlayers = false
            }
    }

let selectedPlayerId = $state('')
    let matchType = $state('indoor')
let season = $state(currentYear)
    let stats: PlayerStats | null = $state(null)
    let prevStats: PlayerStats | null = $state(null)
    let history: MatchHistory[] = $state([])
let loadingStats = $state(false)
    let statsError = $state('')

    async function fetchStats() {
        if (!selectedPlayerId) return
            loadingStats = true
                statsError = ''
                try {
                    stats = await getPlayerStats(selectedPlayerId, matchType, season)
                        history = await getPlayerHistory(selectedPlayerId, matchType, season)
                        try {
                            prevStats = await getPlayerStats(selectedPlayerId, matchType, season - 1)
                        } catch {
                            prevStats = null
                        }
                } catch {
                    statsError = 'Failed to load player stats.'
                        stats = null
                } finally {
                    loadingStats = false
                }
    }

$effect(() => { fetchPlayers() })

    $effect(() => {
            selectedPlayerId
            matchType
            season
            fetchStats()
            })

let newPlayerName = $state('')
let addSuccess = $state('')
let addError = $state('')

async function handleAddPlayer() {
    addSuccess = ''
        addError = ''
        try {
            await createPlayer(newPlayerName)
                addSuccess = `✅ Added ${newPlayerName}`
                newPlayerName = ''
                await fetchPlayers()
        } catch {
            addError = 'Failed to add player.'
        }
}

let managePlayerId = $state('')
let newName = $state('')
let manageSuccess = $state('')
let manageError = $state('')

async function handleRename() {
    manageSuccess = ''
        manageError = ''
        try {
            await updatePlayerName(managePlayerId, newName)
                manageSuccess = '✅ Renamed successfully'
                await fetchPlayers()
        } catch {
            manageError = 'Failed to rename player.'
        }
}

async function handleDelete() {
    manageSuccess = ''
        manageError = ''
        try {
            await deletePlayer(managePlayerId)
                manageSuccess = '✅ Player deleted'
                managePlayerId = ''
                await fetchPlayers()
        } catch {
            manageError = 'Failed to delete player.'
        }
}

function delta(current: number, previous: number | null): { text: string, type: 'positive' | 'negative' | 'neutral' } {
    if (previous === null) return { text: '', type: 'neutral' }
    const diff = current - previous
        if (diff === 0) return { text: '±0', type: 'neutral' }
    return diff > 0
        ? { text: `+${diff}`, type: 'positive' }
    : { text: `${diff}`, type: 'negative' }
}

function calculateMmr(avgPoints: number, efficiencyRate: number): number {
    return avgPoints * efficiencyRate
}

function getRank(played: number, points: number, efficiencyRate: number): string {
    if (played < 10) return 'Unranked'
        const avgPoints = played > 0 ? points / played : 0
            const mmr = calculateMmr(avgPoints, efficiencyRate)
            const ranks: [string, number, number][] = [
            ['Iron I',       0,    0.1],
            ['Iron II',      0.1,  0.2],
            ['Iron III',     0.2,  0.3],
            ['Bronze I',     0.3,  0.4],
            ['Bronze II',    0.4,  0.5],
            ['Bronze III',   0.5,  0.6],
            ['Silver I',     0.6,  0.7],
            ['Silver II',    0.7,  0.8],
            ['Silver III',   0.8,  0.9],
            ['Gold I',       0.9,  1.0],
            ['Gold II',      1.0,  1.1],
            ['Gold III',     1.1,  1.2],
            ['Platinum I',   1.2,  1.3],
            ['Platinum II',  1.3,  1.4],
            ['Platinum III', 1.4,  1.5],
            ['Diamond I',    1.5,  1.6],
            ['Diamond II',   1.6,  1.7],
            ['Diamond III',  1.7,  1.8],
            ['Spiker',       1.8,  1.9],
            ['Ace',          1.9,  2.0],
            ['Sensei',       2.0,  Infinity],
            ]
                for (const [name, low, high] of ranks) {
                    if (mmr >= low && mmr < high) return name
                }
            return 'Iron I'
}
</script>

<div class="page">
<h1>👥 Players</h1>

<div class="tabs">
<button class:active={activeTab === 'profile'} onclick={() => activeTab = 'profile'}>Player Profile</button>
<button class:active={activeTab === 'add'} onclick={() => activeTab = 'add'}>Add Player</button>
<button class:active={activeTab === 'manage'} onclick={() => activeTab = 'manage'}>Manage Players</button>
</div>

<!-- Profile Tab -->
{#if activeTab === 'profile'}
<div class="tab-content">
{#if loadingPlayers}
<p>Loading players...</p>
{:else if players.length === 0}
<p>No players yet!</p>
{:else}
<div class="filters">
<select bind:value={selectedPlayerId}>
<option value="">Select a player</option>
{#each players as player}
<option value={player.id}>{player.name}</option>
{/each}
</select>
<select bind:value={matchType}>
<option value="indoor">Indoor</option>
<option value="beach">Beach</option>
</select>
<input type="number" min="2023" max={currentYear} bind:value={season} />
</div>

{#if !selectedPlayerId}
<p>Select a player to view their stats.</p>
{:else if loadingStats}
<p>Loading stats...</p>
{:else if statsError}
<p class="error">{statsError}</p>
{:else if stats}
<div class="stats-grid">
{#each [
    { label: 'Matches Played', value: stats.played, prev: prevStats?.played ?? null },
        { label: 'Wins', value: stats.wins, prev: prevStats?.wins ?? null },
        { label: 'Losses', value: stats.losses, prev: prevStats?.losses ?? null },
        { label: 'OTL', value: stats.otl, prev: prevStats?.otl ?? null },
        { label: 'Points', value: stats.points, prev: prevStats?.points ?? null },
        { label: 'Win Rate', value: Math.round(stats.win_rate * 100), prev: prevStats ? Math.round(prevStats.win_rate * 100) : null, suffix: '%' },
        { label: 'Win Streak', value: stats.streak, prev: null },
        { label: 'Longest Streak', value: stats.longest_streak, prev: prevStats?.longest_streak ?? null },
] as stat}
{@const d = delta(stat.value, stat.prev)}
<div class="stat-card">
<span class="stat-label">{stat.label}</span>
<span class="stat-value">{stat.value}{stat.suffix ?? ''}</span>
{#if d.text}
<span class="stat-delta {d.type}">{d.text}</span>
{/if}
</div>
{/each}
</div>

<div class="rank-section">
<h3>Rank</h3>
<img
src={`/assets/${getRank(stats.played, stats.points, stats.efficiency_rate)}.png`}
alt={getRank(stats.played, stats.points, stats.efficiency_rate)}
width="160"
/>
<p class="rank-name">{getRank(stats.played, stats.points, stats.efficiency_rate)}</p>
</div>

<div class="history">
<h3>Match History</h3>
{#if history.length === 0}
<p>No completed matches this season.</p>
{:else}
{#each history as match}
{@const myScore = match.color === 'blue' ? match.blue_score : match.red_score}
{@const theirScore = match.color === 'blue' ? match.red_score : match.blue_score}
{@const won = myScore > theirScore}
{@const isOtl = Math.abs(match.blue_score - match.red_score) === 2 && !won}
<div class="history-row" class:win={won} class:otl={isOtl} class:loss={!won && !isOtl}>
<span>{won ? '✅ Win' : isOtl ? '⚠️ OTL' : '❌ Loss'}</span>
<span>{myScore} : {theirScore}</span>
<span>{match.color} team</span>
<span>{match.created_at.slice(0, 10)}</span>
</div>
{/each}
{/if}
</div>
{/if}
{/if}
</div>

<!-- Add Player Tab -->
{:else if activeTab === 'add'}
<div class="tab-content">
<h2>Add New Player</h2>
{#if auth.isAuthenticated}
<div class="form">
<input type="text" placeholder="Player name" bind:value={newPlayerName} />
<button onclick={handleAddPlayer} disabled={!newPlayerName}>Add Player</button>
</div>
{#if addSuccess}<p class="success">{addSuccess}</p>{/if}
{#if addError}<p class="error">{addError}</p>{/if}
{:else}
<p>You must be <a href="/login">logged in</a> to add players.</p>
{/if}
</div>

<!-- Manage Players Tab -->
{:else if activeTab === 'manage'}
<div class="tab-content">
<h2>Manage Players</h2>
{#if !auth.isAuthenticated}
<p>You must be <a href="/login">logged in</a> to manage players.</p>
{:else if players.length === 0}
<p>No players to manage.</p>
{:else}
<select bind:value={managePlayerId}>
<option value="">Select a player</option>
{#each players as player}
<option value={player.id}>{player.name}</option>
{/each}
</select>

{#if managePlayerId}
<div class="manage-actions">
<div class="form">
<h3>✏️ Rename</h3>
<input type="text" placeholder="New name" bind:value={newName} />
<button onclick={handleRename} disabled={!newName}>Rename</button>
</div>

<div class="danger-zone">
<h3>🗑️ Delete</h3>
<p>This will permanently delete this player.</p>
<button class="danger" onclick={handleDelete}>Confirm Delete</button>
</div>
</div>
{/if}

{#if manageSuccess}<p class="success">{manageSuccess}</p>{/if}
{#if manageError}<p class="error">{manageError}</p>{/if}
{/if}
</div>
{/if}
</div>

<style>
.page { padding: 2rem; }

.tabs {
display: flex;
gap: 0.5rem;
     margin-bottom: 1.5rem;
     border-bottom: 2px solid #eee;
     padding-bottom: 0.5rem;
}

.tabs button {
padding: 0.5rem 1rem;
border: none;
background: none;
cursor: pointer;
        font-size: 1rem;
color: #666;
       border-radius: 4px 4px 0 0;
}

.tabs button.active {
color: #ff6b35;
       font-weight: 600;
       border-bottom: 2px solid #ff6b35;
}

.filters {
display: flex;
gap: 1rem;
     margin-bottom: 1.5rem;
}

select, input {
padding: 0.5rem;
         font-size: 1rem;
         border-radius: 4px;
border: 1px solid #ccc;
}

.stats-grid {
display: grid;
         grid-template-columns: repeat(4, 1fr);
gap: 1rem;
     margin-bottom: 2rem;
}

.stat-card {
display: flex;
         flex-direction: column;
padding: 1rem;
         border-radius: 8px;
background: #1a1a2e;
border: 1px solid #2a2a3e;
}

.stat-label {
    font-size: 0.85rem;
color: #aaa;
       margin-bottom: 0.25rem;
}

.stat-value {
    font-size: 1.5rem;
    font-weight: 600;
color: white;
}

.stat-delta {
    font-size: 0.85rem;
    margin-top: 0.25rem;
    font-weight: 500;
}

.stat-delta.positive { color: #4caf50; }
.stat-delta.negative { color: #f44336; }
.stat-delta.neutral  { color: #888; }

.rank-section {
display: flex;
         flex-direction: column;
         align-items: center;
         margin-bottom: 2rem;
gap: 0.5rem;
}

.rank-section h3 {
margin: 0;
color: #444;
}

.rank-name {
    font-size: 1.1rem;
    font-weight: 600;
color: #ff6b35;
margin: 0;
}

.history { margin-top: 1.5rem; }

.history-row {
display: flex;
gap: 2rem;
padding: 0.5rem 1rem;
         border-radius: 4px;
         margin-bottom: 0.5rem;
}

.win  { background: #e8f5e9; }
.otl  { background: #fff8e1; }
.loss { background: #fce4ec; }

.form {
display: flex;
gap: 1rem;
     align-items: center;
     margin-bottom: 1rem;
}

.manage-actions {
display: flex;
         flex-direction: column;
gap: 2rem;
     margin-top: 1.5rem;
}

.danger-zone {
border: 1px solid #ffcdd2;
        border-radius: 8px;
padding: 1rem;
background: #fff5f5;
}

button {
padding: 0.5rem 1rem;
         border-radius: 4px;
border: none;
cursor: pointer;
background: #ff6b35;
color: white;
       font-size: 1rem;
}

button:disabled {
opacity: 0.5;
cursor: not-allowed;
       }

button.danger { background: #e53935; }

.success { color: green; }
.error   { color: red; }
</style>
